# This is a basic workflow that is manually triggered

name: Manual workflow 1

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      note:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Additional note for the release (Optional)'
        # Input has to be provided for the workflow to run
        required: false
      name:
        required: true
        type: choice
        description: 'Which version to bump? (major.minor.patch)'
        default: 'minor'
        options: 
        - major
        - minor
        - patch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-tag:
    env:
      GITHUB_TOKEN: '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'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Fetch Latest Tag
      id: fetch-tags
      uses: actions/github-script@v5
      with:
        debug: true
        script: |
          github.rest.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
    - name: Get Latest Tag
      run: echo "${{steps.fetch-tags.outputs.data[0].name}}"
